---
- name: Create Nginx image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Nginx image
      community.docker.docker_image:
        name: ansiblebook/nginx-ghost
        source: build
        build:
          path: nginx
