- name: Run ghost locally
  hosts: localhost
  tasks:
    - name: Create Nginx image
      community.docker.docker_image:
        name: ansiblebook/nginx-ghost
        source: build
        build:
          path: nginx

    - name: Create certs
      ansible.builtin.command: >
        openssl req -new -x509 -nodes
        -out certs/nginx.crt -keyout certs/nginx.key
        -subj '/CN=localhost' -days 3650
        creates=certs/nginx.crt

    - name: Bring up services
      community.docker.docker_compose:
        project_src: .
        state: present
