- name: Publish images to local docker registry
  hosts: localhost
  gather_facts: false
  vars:
    repo_port: 6000
    repo: "localhost:{{repo_port}}"
    image: ansiblebook/nginx-ghost
  tasks:
    - name: Start a registry locally
      community.docker.docker_container:
        name: registry
        image: registry:2
        ports: "{{ repo_port }}:5000"
    - name: Debug
      ansible.builtin.debug:
        msg: name={{ image }} repo={{ repo }}/{{ image }}
    - name: Tag the nginx-ghost image to the repository
      community.docker.docker_image:
        name: "{{ image }}"
        repository: "{{ repo }}/{{ image }}"
        push: true
        source: pull
