- name: Publish images to docker hub
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: username
      prompt: Enter Docker Registry username
      private: false
    - name: password
      prompt: Enter Docker Registry password=
      private: true
  tasks:
    - name: Authenticate with repository
      community.docker.docker_login:
        username: "{{ username }}"
        password: "{{ password }}"
    - name: Push image up
      community.docker.docker_image:
        name: ansiblebook/nginx-ghost
        source: pull
        repository: 1672gilbert/nginx-ghost
        push: true
