# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "postgres" do |postgres|
        postgres.vm.box = "generic/ubuntu2004" # x86
        # postgres.vm.box = "starboard/ubuntu-arm64-20.04.5" # arm64
        postgres.vm.network "private_network", ip: "192.168.33.9"
    end
    config.vm.define "ghost" do |ghost|
        ghost.vm.box = "generic/ubuntu2004" # x86
        # ghost.vm.box = "starboard/ubuntu-arm64-20.04.5" # arm64
        ghost.vm.network "private_network", ip: "192.168.33.10"
    end

    config.vm.provider "vmware_desktop" do |v|
        v.gui = true
        v.linked_clone = false
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
        v.memory = 1024
    end

end

